Matrix and Vector: 

In [30]:
import numpy as np

v = [1, 2, 3]
v = reshape(v, (3, 1))
m, n = v.shape
print(m, n)

x = range(12)
X = reshape(x, (4, 3))
m, n = X.shape
print(m, n)

e1_1 = X[0][0]  # Zero-based
print(e1_1)



3 1
4 3
0


In [34]:
A = np.array([[1, 2, 4], [5, 3, 2]])
B = np.array([[1, 3, 4], [1, 1, 1]])

s = 2

add_AB = A + B
print(add_AB)

sub_AB = A - B
print(sub_AB)

mult_As = A * s
print(mult_As)

div_As = A / s
print(div_As)

add_As = A + s
print(add_As)

[[2 5 8]
 [6 4 3]]
[[ 0 -1  0]
 [ 4  2  1]]
[[ 2  4  8]
 [10  6  4]]
[[ 0.5  1.   2. ]
 [ 2.5  1.5  1. ]]
[[3 4 6]
 [7 5 4]]


In [42]:
print(A.shape)

v = np.array([[1], [2], [3]])
print(v.shape)

mult_Av = A.dot(v)
print(mult_Av.shape)

(2, 3)
(3, 1)
(2, 1)


In [45]:
print(A.shape)
I = np.identity(3, integer)
print(A)
print(A.dot(I))

(2, 3)
[[1 2 4]
 [5 3 2]]
[[1 2 4]
 [5 3 2]]
